name: Build and Test

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: out
          path: out/