name: Deploy

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/

  deploy-test:
    if: github.ref != 'refs/heads/main'
    name: Deploy to Test
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://david-test.eadie.net
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://david.eadie.net
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./
