name: Deploy - Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    uses: ./.github/workflows/zz-deploy.yml
    secrets: inherit
    with:
      environment: Production
      url: https://david.eadie.net