name: Deploy

on:
  push:

jobs:
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.eadie.net
        username: bot@eadie.net
        password: ${{ secrets.ftp_password }}
        server-dir: ./test/

  deploy-prod:
    name: Deploy to Production
    needs: deploy-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.eadie.net
        username: bot@eadie.net
        password: ${{ secrets.ftp_password }}
        server-dir: ./