name: Deploy

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

  deploy-test:
    name: Deploy to Test
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.eadie.net
          username: bot@eadie.net
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: ./test/

  deploy-prod:
    name: Deploy to Production
    needs: deploy-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.eadie.net
          username: bot@eadie.net
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: ./
